import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { checkCurrent, evaluateMerge, mergeCurrent } from '../src/civicline-merge-authority.mjs';
import { acquireStateLock } from '../integrations/openclaw/execution-harness/state-lock.mjs';
const head='a'.repeat(40),base='b'.repeat(40),now=Date.now(), issue=3000;
const deploymentReceipt={head,imageDigest:`sha256:${'c'.repeat(64)}`,servingRevision:'clerk-uat--0000003'};
const deploymentDigest=createHash('sha256').update(JSON.stringify(deploymentReceipt)).digest('hex');
const browserReceipt={...deploymentReceipt,terminalOutcome:'PASS'};
const browserDigest=createHash('sha256').update(JSON.stringify(browserReceipt)).digest('hex');
const browserRef='civicline-browser-proof',deploymentRef='civicline-current-deployment';
const charter={agentId:'civicline-cto',mode:'routine',repositories:['jgraham310/local-government'],autonomousOperations:['merge_green_pr'],protocolRequired:['merge_green_pr'],boundedAuthority:{merge:true,production:false,customerData:false,prohibitedOperations:[]}};
const state={records:{'cto:civicline':{status:'active',authorityBoundary:{allowedActions:['internal_update']},authorizedOperations:['merge_green_pr'],currentDeploymentEvidenceRef:deploymentRef,evidenceRefs:['civicline-merge-staging-grant-20260928',browserRef,deploymentRef]}},evidence:{'civicline-merge-staging-grant-20260928':{status:'verified'},[browserRef]:{status:'verified',artifact:`sha256:${browserDigest}`},[deploymentRef]:{status:'verified',artifact:`sha256:${deploymentDigest}`}}};
const pr={number:2981,state:'open',draft:false,mergeable:true,user:{login:'author'},head:{sha:head},base:{sha:base}};
const checks=[{bucket:'pass'},{bucket:'pass'}];
const url='https://github.com/jgraham310/local-government/pull/2981#review';
const proof={repository:'jgraham310/local-government',pr:2981,head,base,review:{head,independent:true,reviewer:'reviewer',url,observedAt:new Date(now).toISOString(),findings:[{id:'review-P2-1',severity:'P2'}]},acceptance:{issueDerived:true,negativeControls:true,deterministicTests:true,head,browserRequired:true,browserTerminalOutcome:'PASS',browserHead:head,browserEvidenceRef:browserRef,deploymentEvidenceRef:deploymentRef},p2Disposition:{head,issue,findingIds:['review-P2-1']}};
const p2Issue={number:issue,state:'open',body:`review-P2-1 ${head} ${url}\nAcceptance test: named\nOwner: CTO\nBlocking-risk exclusion: reviewed`};
const reviews=[{state:'APPROVED',commit_id:head,html_url:url,user:{login:'reviewer'},submitted_at:new Date(now).toISOString()}];
const threads={nodes:[],pageInfo:{hasNextPage:false}};
const baseInput={source:charter,live:charter,state,pr,checks,proof,p2Issue,reviews,threads,browserReceipt,browserDigest,deploymentReceipt,deploymentDigest};
const check=(override={})=>evaluateMerge({...baseInput,...override},now);
assert.equal(check().allowed,true);
assert.equal(check({state:{...state,records:{'cto:civicline':{...state.records['cto:civicline'],authorizedOperations:[]}}}}).reason,'authority_or_workstate');
assert.equal(check({proof:{...proof,review:{...proof.review,independent:true}},reviews:[]}).reason,'exact_head_review');
assert.equal(check({proof:{...proof,acceptance:{...proof.acceptance,browserRequired:false}}}).reason,'acceptance_proof');
assert.equal(check({threads:{nodes:[{isResolved:false}],pageInfo:{hasNextPage:false}}}).reason,'unresolved_review_threads');
assert.equal(check({threads:{nodes:[],pageInfo:{hasNextPage:true}}}).reason,'unresolved_review_threads');
assert.equal(check({reviews:[{...reviews[0],user:{login:'author'}}]}).reason,'exact_head_review');
assert.equal(check({reviews:[{...reviews[0],commit_id:base}]}).reason,'exact_head_review');
assert.equal(check({reviews:[...reviews,{...reviews[0],state:'CHANGES_REQUESTED',submitted_at:new Date(now+1).toISOString()}]}).reason,'exact_head_review');
assert.equal(check({browserDigest:'0'.repeat(64)}).reason,'acceptance_proof');
assert.equal(check({deploymentDigest:'0'.repeat(64)}).reason,'acceptance_proof');
assert.equal(check({deploymentReceipt:{...deploymentReceipt,head:base}}).reason,'acceptance_proof');
assert.equal(check({browserReceipt:{...browserReceipt,imageDigest:`sha256:${'d'.repeat(64)}`}}).reason,'acceptance_proof');
assert.equal(check({browserReceipt:{...browserReceipt,servingRevision:'older-revision'}}).reason,'acceptance_proof');
assert.equal(check({state:{...state,records:{'cto:civicline':{...state.records['cto:civicline'],currentDeploymentEvidenceRef:'successor'}}}}).reason,'acceptance_proof');
for(const severity of ['P0','P1']) assert.equal(check({proof:{...proof,review:{...proof.review,findings:[{id:'block',severity}]}}}).reason,'blocking_review_finding');
assert.equal(check({proof:{...proof,review:{...proof.review,findings:[{id:'review-P2-1',severity:'P2',securityOrTenantRisk:true}]}}}).reason,'launch_critical_p2');
assert.equal(check({pr:{...pr,head:{sha:base}}}).reason,'stale_or_invalid_head');
assert.equal(check({checks:[{bucket:'fail'}]}).reason,'exact_head_ci');
assert.equal(check({proof:{...proof,review:{...proof.review,head:base}}}).reason,'exact_head_review');
assert.equal(check({proof:{...proof,review:{...proof.review,observedAt:new Date(now-31*60*1000).toISOString()}}}).reason,'exact_head_review');
assert.equal(check({proof:{...proof,acceptance:{...proof.acceptance,negativeControls:false}}}).reason,'acceptance_proof');
assert.equal(check({p2Issue:null}).reason,'p2_follow_up_missing');
assert.equal(check({live:{...charter,boundedAuthority:{...charter.boundedAuthority,merge:false}}}).reason,'authority_or_workstate');
assert.equal(check({state:{...state,records:{'cto:civicline':{status:'blocked',evidenceRefs:[]}}}}).reason,'authority_or_workstate');
const fixture=mkdtempSync(join(tmpdir(),'civicline-merge-'));
try {
  const files=Object.fromEntries(['source','live','state','proof','browser','deployment'].map(n=>[n,join(fixture,`${n}.json`)]));
  for (const [name,value] of Object.entries({source:charter,live:charter,state,proof,browser:browserReceipt,deployment:deploymentReceipt}))
    writeFileSync(files[name],JSON.stringify(value));
  writeFileSync(files.proof,JSON.stringify({...proof,acceptance:{...proof.acceptance,browserReceiptPath:files.browser,deploymentReceiptPath:files.deployment}}));
  const calls=[];
  const runner=(_bin,args)=>{
    calls.push(args);
    let value;
    if (args[0]==='api' && args[1]===`repos/jgraham310/local-government/pulls/${pr.number}`) value=pr;
    else if (args[0]==='pr' && args[1]==='checks') value=checks;
    else if (args[0]==='api' && args[1]?.endsWith('/reviews?per_page=100')) value=reviews;
    else if (args[0]==='api' && args[1]==='graphql') value={data:{repository:{pullRequest:{reviewThreads:threads}}}};
    else if (args[0]==='api' && args[1]?.endsWith(`/issues/${issue}`)) value=p2Issue;
    else throw new Error(`unexpected GitHub call: ${args.join(' ')}`);
    return {status:0,stdout:JSON.stringify(value),stderr:''};
  };
  const options={sourceFile:files.source,liveFile:files.live,stateFile:files.state,runner,now};
  assert.equal(checkCurrent(pr.number,files.proof,options).allowed,true);
  assert.equal(calls.some(args=>args[1]==='graphql'),true,'live review threads must be queried');
  assert.equal(calls.some(args=>args[1]?.endsWith('/reviews?per_page=100')),true,'live reviews must be queried');
  const lockedRunner=(_bin,args)=>{
    if (args[0]==='pr' && args[1]==='merge') {
      assert.throws(()=>acquireStateLock(files.state),/State is busy/, 'WorkState must remain locked through merge');
      assert.equal(args.includes('--match-head-commit'),true);
      assert.equal(args.at(-1),head);
      return {status:0,stdout:'merged',stderr:''};
    }
    return runner(_bin,args);
  };
  assert.equal(mergeCurrent(pr.number,files.proof,{...options,runner:lockedRunner}).status,'merge_command_succeeded');
  const releaseAfterMerge=acquireStateLock(files.state);
  releaseAfterMerge();
  writeFileSync(files.state,JSON.stringify({...state,records:{'cto:civicline':{...state.records['cto:civicline'],authorizedOperations:[]}}}));
  calls.length=0;
  assert.equal(checkCurrent(pr.number,files.proof,options).reason,'authority_or_workstate');
  assert.equal(calls.length,0,'held WorkState must stop before GitHub calls');
} finally { rmSync(fixture,{recursive:true,force:true}); }
console.log('CivicLine merge authority tests: passed');
