import assert from 'node:assert/strict';
import { evaluateMerge } from '../src/civicline-merge-authority.mjs';
const head='a'.repeat(40),base='b'.repeat(40),now=Date.now(), issue=3000;
const charter={agentId:'civicline-cto',mode:'routine',repositories:['jgraham310/local-government'],autonomousOperations:['merge_green_pr'],protocolRequired:['merge_green_pr'],boundedAuthority:{merge:true,production:false,customerData:false,prohibitedOperations:[]}};
const state={records:{'cto:civicline':{status:'active',evidenceRefs:['civicline-merge-staging-grant-20260928']}},evidence:{'civicline-merge-staging-grant-20260928':{status:'verified'}}};
const pr={number:2981,state:'open',draft:false,mergeable:true,head:{sha:head},base:{sha:base}};
const checks=[{bucket:'pass'},{bucket:'pass'}];
const url='https://github.com/jgraham310/local-government/pull/2981#review';
const proof={repository:'jgraham310/local-government',pr:2981,head,base,review:{head,independent:true,url,observedAt:new Date(now).toISOString(),findings:[{id:'review-P2-1',severity:'P2'}]},acceptance:{issueDerived:true,negativeControls:true,deterministicTests:true,head,browserRequired:true,browserTerminalOutcome:'PASS',browserHead:head},p2Disposition:{head,issue,reviewThreadsResolved:true,findingIds:['review-P2-1']}};
const p2Issue={number:issue,state:'open',body:`review-P2-1 ${head} ${url}\nAcceptance test: named\nOwner: CTO\nBlocking-risk exclusion: reviewed`};
const baseInput={source:charter,live:charter,state,pr,checks,proof,p2Issue};
const check=(override={})=>evaluateMerge({...baseInput,...override},now);
assert.equal(check().allowed,true);
for(const severity of ['P0','P1']) assert.equal(check({proof:{...proof,review:{...proof.review,findings:[{id:'block',severity}]}}}).reason,'blocking_review_finding');
assert.equal(check({proof:{...proof,review:{...proof.review,findings:[{id:'review-P2-1',severity:'P2',securityOrTenantRisk:true}]}}}).reason,'launch_critical_p2');
assert.equal(check({pr:{...pr,head:{sha:base}}}).reason,'stale_or_invalid_head');
assert.equal(check({checks:[{bucket:'fail'}]}).reason,'exact_head_ci');
assert.equal(check({proof:{...proof,review:{...proof.review,head:base}}}).reason,'exact_head_review');
assert.equal(check({proof:{...proof,review:{...proof.review,observedAt:new Date(now-31*60*1000).toISOString()}}}).reason,'exact_head_review');
assert.equal(check({proof:{...proof,acceptance:{...proof.acceptance,negativeControls:false}}}).reason,'acceptance_proof');
assert.equal(check({p2Issue:null}).reason,'p2_follow_up_missing');
assert.equal(check({live:{...charter,boundedAuthority:{...charter.boundedAuthority,merge:false}}}).reason,'authority_or_workstate');
assert.equal(check({state:{...state,records:{'cto:civicline':{status:'blocked',evidenceRefs:[]}}}}).reason,'authority_or_workstate');
console.log('CivicLine merge authority tests: passed');
